### ISSUE TITLE
Create exit_from_groups() in Group class

### ISSUE THREAD

**Issue by NavpreetDevpuri** [Tithibots/tithiwa#43]
similar to https://github.com/Tithibots/tithiwa/issues/35
`exit_from_groups(groups)`

**Comment by Vipul-Bajaj** [comment]
I would like to work on this

**Comment by NavpreetDevpuri** [comment]
if you can do that. 
You need to go through all groups and exit only from given `groups`

And https://github.com/Tithibots/tithiwa/issues/35 is for exiting all groups 
I suggest first do that then just put some condition into it to make `exit_from_groups(groups)` just like I did in `make_group_admins()` [here](https://github.com/Tithibots/tithiwa/blob/main/tithiwa/group.py#L54-L75) it's almost the same as [this](https://github.com/Tithibots/tithiwa/blob/main/tithiwa/group.py#L35-L52) which is going through all members.

**Comment by Vipul-Bajaj** [comment]
I don't think it is that straightforward because we have to look at all the chats and identify which is a group and which is not and then implement the logic for exiting from the group.
Currently, I am trying to exit from one group and then will try to do exit from multiple groups.
Once that is done, one can write a logic to scrape all the groups, and pass to the function I am writing

**Comment by NavpreetDevpuri** [comment]
I tried, and i found that it's better to just go through all chats and somehow detect which one are groups and select those chats and then we can just exit all groupa by just one click because whatsapp have that feature just select multiple groups and presss exit all groups option.

**Comment by Vipul-Bajaj** [comment]
As far as I have explored selecting multiple groups is available on the mobile apps and not on the web version.
